import type { ElementType } from "react";
import {
  FaBehance,
  FaDiscord,
  FaDribbble,
  FaEnvelope,
  FaFacebookF,
  FaFlickr,
  FaGithub,
  FaGlobe,
  FaGoogle,
  FaInstagram,
  FaLinkedinIn,
  FaMastodon,
  FaMedium,
  FaPinterest,
  FaQuora,
  FaReddit,
  FaSkype,
  FaSnapchat,
  FaSpotify,
  FaTelegram,
  FaTripadvisor,
  FaTumblr,
  FaTwitter,
  FaVimeo,
  FaWhatsapp,
  FaXing,
  FaYelp,
  FaYoutube,
  FaTiktok,
} from "react-icons/fa";
import { FaBluesky, FaThreads, FaXTwitter } from "react-icons/fa6";

export const SOCIAL_PLATFORM_IDS = [
  "facebook",
  "instagram",
  "twitter",
  "x",
  "linkedin",
  "youtube",
  "whatsapp",
  "telegram",
  "tiktok",
  "pinterest",
  "snapchat",
  "threads",
  "bluesky",
  "reddit",
  "discord",
  "github",
  "dribbble",
  "behance",
  "medium",
  "vimeo",
  "spotify",
  "skype",
  "tumblr",
  "flickr",
  "quora",
  "yelp",
  "tripadvisor",
  "google",
  "xing",
  "mastodon",
  "email",
  "website",
] as const;

export type SocialPlatformId = (typeof SOCIAL_PLATFORM_IDS)[number];

export type SocialPlatformOption = {
  id: SocialPlatformId;
  label: string;
};

export const SOCIAL_PLATFORM_OPTIONS: SocialPlatformOption[] = [
  { id: "facebook", label: "Facebook" },
  { id: "instagram", label: "Instagram" },
  { id: "twitter", label: "Twitter" },
  { id: "x", label: "X" },
  { id: "linkedin", label: "LinkedIn" },
  { id: "youtube", label: "YouTube" },
  { id: "whatsapp", label: "WhatsApp" },
  { id: "telegram", label: "Telegram" },
  { id: "tiktok", label: "TikTok" },
  { id: "pinterest", label: "Pinterest" },
  { id: "snapchat", label: "Snapchat" },
  { id: "threads", label: "Threads" },
  { id: "bluesky", label: "Bluesky" },
  { id: "reddit", label: "Reddit" },
  { id: "discord", label: "Discord" },
  { id: "github", label: "GitHub" },
  { id: "dribbble", label: "Dribbble" },
  { id: "behance", label: "Behance" },
  { id: "medium", label: "Medium" },
  { id: "vimeo", label: "Vimeo" },
  { id: "spotify", label: "Spotify" },
  { id: "skype", label: "Skype" },
  { id: "tumblr", label: "Tumblr" },
  { id: "flickr", label: "Flickr" },
  { id: "quora", label: "Quora" },
  { id: "yelp", label: "Yelp" },
  { id: "tripadvisor", label: "Tripadvisor" },
  { id: "google", label: "Google" },
  { id: "xing", label: "Xing" },
  { id: "mastodon", label: "Mastodon" },
  { id: "email", label: "Email" },
  { id: "website", label: "Website" },
];

export const SOCIAL_PLATFORM_ICONS: Record<SocialPlatformId, ElementType> = {
  facebook: FaFacebookF,
  instagram: FaInstagram,
  twitter: FaTwitter,
  x: FaXTwitter,
  linkedin: FaLinkedinIn,
  youtube: FaYoutube,
  whatsapp: FaWhatsapp,
  telegram: FaTelegram,
  tiktok: FaTiktok,
  pinterest: FaPinterest,
  snapchat: FaSnapchat,
  threads: FaThreads,
  bluesky: FaBluesky,
  reddit: FaReddit,
  discord: FaDiscord,
  github: FaGithub,
  dribbble: FaDribbble,
  behance: FaBehance,
  medium: FaMedium,
  vimeo: FaVimeo,
  spotify: FaSpotify,
  skype: FaSkype,
  tumblr: FaTumblr,
  flickr: FaFlickr,
  quora: FaQuora,
  yelp: FaYelp,
  tripadvisor: FaTripadvisor,
  google: FaGoogle,
  xing: FaXing,
  mastodon: FaMastodon,
  email: FaEnvelope,
  website: FaGlobe,
};

export const isSocialPlatformId = (value: unknown): value is SocialPlatformId =>
  typeof value === "string" &&
  (SOCIAL_PLATFORM_IDS as readonly string[]).includes(value);

export const getSocialPlatformIcon = (label: string): ElementType =>
  isSocialPlatformId(label) ? SOCIAL_PLATFORM_ICONS[label] : FaGlobe;
